In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("winequality-red.csv")

In [3]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5


In [4]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [5]:
X=df.drop('quality',axis=1)
y=df['quality']

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
model1 = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred1))

print("\nClassification Report")
print(classification_report(y_test,y_pred1))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred1))

Accuracy: 0.546875

Classification Report
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        10
           5       0.59      0.68      0.63       130
           6       0.51      0.55      0.53       132
           7       0.54      0.36      0.43        42
           8       0.00      0.00      0.00         5

    accuracy                           0.55       320
   macro avg       0.27      0.26      0.26       320
weighted avg       0.52      0.55      0.53       320


Confusion Matrix
[[ 0  0  0  1  0  0]
 [ 0  0  4  6  0  0]
 [ 0  2 88 40  0  0]
 [ 1  0 49 72 10  0]
 [ 0  0  7 20 15  0]
 [ 0  0  1  1  3  0]]


/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metri

In [10]:
model2 = KNeighborsClassifier(n_neighbors=10,metric='manhattan')
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred2))

print("\nClassification Report")
print(classification_report(y_test,y_pred2))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred2))

Accuracy: 0.571875

Classification Report
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        10
           5       0.61      0.75      0.67       130
           6       0.55      0.54      0.54       132
           7       0.48      0.36      0.41        42
           8       0.00      0.00      0.00         5

    accuracy                           0.57       320
   macro avg       0.27      0.27      0.27       320
weighted avg       0.54      0.57      0.55       320


Confusion Matrix
[[ 0  0  1  0  0  0]
 [ 0  0  7  3  0  0]
 [ 0  1 97 31  1  0]
 [ 0  0 51 71 10  0]
 [ 0  0  3 24 15  0]
 [ 0  0  0  0  5  0]]


/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metri

In [11]:
for k in range(1,21):

    model = KNeighborsClassifier(n_neighbors=k,metric='manhattan')
    model.fit(X_train,y_train)

    y_pred = model.predict(X_test)

    print(k,accuracy_score(y_test,y_pred))

1 0.625
2 0.55625
3 0.55
4 0.584375
5 0.565625
6 0.540625
7 0.55
8 0.56875
9 0.565625
10 0.571875
11 0.565625
12 0.559375
13 0.578125
14 0.571875
15 0.590625
16 0.553125
17 0.5625
18 0.55
19 0.5625
20 0.553125


In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = KNeighborsClassifier(n_neighbors=5,weights='distance')

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.625
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        10
           5       0.69      0.70      0.70       130
           6       0.58      0.64      0.61       132
           7       0.58      0.60      0.59        42
           8       0.00      0.00      0.00         5

    accuracy                           0.62       320
   macro avg       0.31      0.32      0.32       320
weighted avg       0.60      0.62      0.61       320

[[ 0  0  0  1  0  0]
 [ 0  0  4  6  0  0]
 [ 0  1 91 37  1  0]
 [ 0  0 35 84 13  0]
 [ 0  0  1 15 25  1]
 [ 0  0  0  1  4  0]]


/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metri