In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('Seed_Data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       210 non-null    float64
 1   P       210 non-null    float64
 2   C       210 non-null    float64
 3   LK      210 non-null    float64
 4   WK      210 non-null    float64
 5   A_Coef  210 non-null    float64
 6   LKG     210 non-null    float64
 7   target  210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [4]:
df.describe()

,A,P,C,LK,WK,A_Coef,LKG,target
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,14.847524,14.559286,0.870999,5.628533,3.258605,3.700201,5.408071,1.000000
std,2.909699,1.305959,0.023629,0.443063,0.377714,1.503557,0.491480,0.818448
min,10.590000,12.410000,0.808100,4.899000,2.630000,0.765100,4.519000,0.000000
25%,12.270000,13.450000,0.856900,5.262250,2.944000,2.561500,5.045000,0.000000
50%,14.355000,14.320000,0.873450,5.523500,3.237000,3.599000,5.223000,1.000000
75%,17.305000,15.715000,0.887775,5.979750,3.561750,4.768750,5.877000,2.000000
max,21.180000,17.250000,0.918300,6.675000,4.033000,8.456000,6.550000,2.000000


In [6]:
df.isnull().sum()

A         0
P         0
C         0
LK        0
WK        0
A_Coef    0
LKG       0
target    0
dtype: int64

In [7]:
df['target'].unique()

array([0, 1, 2])

In [8]:
X = df.drop('target',axis=1)
y = df['target']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
model1 = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred1))

print("\nClassification Report")
print(classification_report(y_test,y_pred1))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred1))

Accuracy: 0.8809523809523809

Classification Report
              precision    recall  f1-score   support

           0       0.75      0.82      0.78        11
           1       1.00      1.00      1.00        14
           2       0.88      0.82      0.85        17

    accuracy                           0.88        42
   macro avg       0.88      0.88      0.88        42
weighted avg       0.88      0.88      0.88        42


Confusion Matrix
[[ 9  0  2]
 [ 0 14  0]
 [ 3  0 14]]


In [12]:
model2 = KNeighborsClassifier(n_neighbors=10,metric='manhattan')
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred2))

print("\nClassification Report")
print(classification_report(y_test,y_pred2))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred2))

Accuracy: 0.8809523809523809

Classification Report
              precision    recall  f1-score   support

           0       0.75      0.82      0.78        11
           1       1.00      1.00      1.00        14
           2       0.88      0.82      0.85        17

    accuracy                           0.88        42
   macro avg       0.88      0.88      0.88        42
weighted avg       0.88      0.88      0.88        42


Confusion Matrix
[[ 9  0  2]
 [ 0 14  0]
 [ 3  0 14]]


In [13]:
for k in range(1,21):

    model = KNeighborsClassifier(n_neighbors=k,metric='manhattan')
    model.fit(X_train,y_train)

    y_pred = model.predict(X_test)

    print(k,accuracy_score(y_test,y_pred))

1 0.9285714285714286
2 0.8571428571428571
3 0.8571428571428571
4 0.8571428571428571
5 0.8809523809523809
6 0.9047619047619048
7 0.9047619047619048
8 0.8809523809523809
9 0.8809523809523809
10 0.8809523809523809
11 0.8809523809523809
12 0.8809523809523809
13 0.8809523809523809
14 0.8809523809523809
15 0.8809523809523809
16 0.8809523809523809
17 0.8809523809523809
18 0.8809523809523809
19 0.8809523809523809
20 0.8809523809523809
