In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [5]:
df = pd.read_csv('Seed_Data.csv')

In [7]:
df.shape

(210, 8)

In [8]:
df.describe()

,A,P,C,LK,WK,A_Coef,LKG,target
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,14.847524,14.559286,0.870999,5.628533,3.258605,3.700201,5.408071,1.000000
std,2.909699,1.305959,0.023629,0.443063,0.377714,1.503557,0.491480,0.818448
min,10.590000,12.410000,0.808100,4.899000,2.630000,0.765100,4.519000,0.000000
25%,12.270000,13.450000,0.856900,5.262250,2.944000,2.561500,5.045000,0.000000
50%,14.355000,14.320000,0.873450,5.523500,3.237000,3.599000,5.223000,1.000000
75%,17.305000,15.715000,0.887775,5.979750,3.561750,4.768750,5.877000,2.000000
max,21.180000,17.250000,0.918300,6.675000,4.033000,8.456000,6.550000,2.000000


In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       210 non-null    float64
 1   P       210 non-null    float64
 2   C       210 non-null    float64
 3   LK      210 non-null    float64
 4   WK      210 non-null    float64
 5   A_Coef  210 non-null    float64
 6   LKG     210 non-null    float64
 7   target  210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [10]:
df.isnull().sum()

A         0
P         0
C         0
LK        0
WK        0
A_Coef    0
LKG       0
target    0
dtype: int64

In [11]:
df.head()

,A,P,C,LK,WK,A_Coef,LKG,target
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,0
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,0
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,0
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,0
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,0


In [12]:
df['target'].unique()

array([0, 1, 2])

In [13]:
X = df.drop('target',axis=1)
y = df['target']

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
model1 = SVC(kernel='linear')
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred1))
print('classification_report:',classification_report(y_test,y_pred1))
print('confusion_matrix:',confusion_matrix(y_test,y_pred1))

accuracy_score: 0.9047619047619048
classification_report:               precision    recall  f1-score   support

           0       0.82      0.82      0.82        11
           1       1.00      1.00      1.00        14
           2       0.88      0.88      0.88        17

    accuracy                           0.90        42
   macro avg       0.90      0.90      0.90        42
weighted avg       0.90      0.90      0.90        42

confusion_matrix: [[ 9  0  2]
 [ 0 14  0]
 [ 2  0 15]]


In [19]:
model2 = SVC(kernel='rbf')
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred2))
print('classification_report:',classification_report(y_test,y_pred2))
print('confusion_matrix:',confusion_matrix(y_test,y_pred2))

accuracy_score: 0.9047619047619048
classification_report:               precision    recall  f1-score   support

           0       0.77      0.91      0.83        11
           1       1.00      1.00      1.00        14
           2       0.93      0.82      0.88        17

    accuracy                           0.90        42
   macro avg       0.90      0.91      0.90        42
weighted avg       0.91      0.90      0.91        42

confusion_matrix: [[10  0  1]
 [ 0 14  0]
 [ 3  0 14]]


In [22]:
model3 = SVC(kernel='poly')
model3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred3))
print('classification_report:',classification_report(y_test,y_pred3))
print('confusion_matrix:',confusion_matrix(y_test,y_pred3))

accuracy_score: 0.8333333333333334
classification_report:               precision    recall  f1-score   support

           0       0.62      0.91      0.74        11
           1       1.00      0.86      0.92        14
           2       0.93      0.76      0.84        17

    accuracy                           0.83        42
   macro avg       0.85      0.84      0.83        42
weighted avg       0.87      0.83      0.84        42

confusion_matrix: [[10  0  1]
 [ 2 12  0]
 [ 4  0 13]]


In [23]:
model4 = SVC(kernel='sigmoid')
model4.fit(X_train,y_train)
y_pred4 = model4.predict(X_test)
print('accuracy_score:',accuracy_score(y_test,y_pred4))
print('classification_report:',classification_report(y_test,y_pred4))
print('confusion_matrix:',confusion_matrix(y_test,y_pred4))

accuracy_score: 0.9047619047619048
classification_report:               precision    recall  f1-score   support

           0       0.82      0.82      0.82        11
           1       1.00      1.00      1.00        14
           2       0.88      0.88      0.88        17

    accuracy                           0.90        42
   macro avg       0.90      0.90      0.90        42
weighted avg       0.90      0.90      0.90        42

confusion_matrix: [[ 9  0  2]
 [ 0 14  0]
 [ 2  0 15]]


In [25]:
kernels = ["linear", "rbf", "poly"]

for k in kernels:
    model = SVC(kernel=k)
    model.fit(X_train, y_train)
    print(k, model.score(X_test, y_test))

linear 0.9047619047619048
rbf 0.9047619047619048
poly 0.8333333333333334
