In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
df = pd.read_csv("iris.csv")

In [4]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [6]:
df.drop(['Id'],axis=1,inplace=True)

In [7]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

In [9]:
df.head()

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [10]:
df.describe()

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667,1.000000
std,0.828066,0.433594,1.764420,0.763161,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [12]:
df.shape

(150, 5)

In [13]:
X = df.drop('Species',axis=1)
y = df['Species']

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
model1 = AdaBoostClassifier(random_state=42)
model1.fit(X_train,y_train)
y_pred1=model1.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))
print("confusion_matrix:",confusion_matrix(y_test,y_pred1))

accuracy_Score: 0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      0.89      0.89         9
           2       0.91      0.91      0.91        11

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

confusion_matrix: [[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]


In [16]:
model2 = GradientBoostingClassifier()
model2.fit(X_train,y_train)
y_pred2=model2.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))
print("confusion_matrix:",confusion_matrix(y_test,y_pred2))

accuracy_Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [17]:
model3 = XGBClassifier()
model3.fit(X_train,y_train)
y_pred3=model3.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))
print("confusion_matrix:",confusion_matrix(y_test,y_pred3))

accuracy_Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [18]:
model4 = CatBoostClassifier()
model4.fit(X_train,y_train)
y_pred4=model4.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred4))
print(classification_report(y_test,y_pred4))
print("confusion_matrix:",confusion_matrix(y_test,y_pred4))

Learning rate set to 0.071017
0:	learn: 1.0144505	total: 59.5ms	remaining: 59.5s
1:	learn: 0.9426321	total: 60.1ms	remaining: 30s
2:	learn: 0.8791473	total: 60.5ms	remaining: 20.1s
3:	learn: 0.8214933	total: 60.9ms	remaining: 15.2s
4:	learn: 0.7788401	total: 61.6ms	remaining: 12.3s
5:	learn: 0.7280627	total: 61.8ms	remaining: 10.2s
6:	learn: 0.6913500	total: 62ms	remaining: 8.79s
7:	learn: 0.6584766	total: 62.2ms	remaining: 7.71s
8:	learn: 0.6235636	total: 62.5ms	remaining: 6.88s
9:	learn: 0.5948198	total: 62.9ms	remaining: 6.23s
10:	learn: 0.5645192	total: 63.1ms	remaining: 5.67s
11:	learn: 0.5372072	total: 63.3ms	remaining: 5.21s
12:	learn: 0.5124436	total: 63.5ms	remaining: 4.82s
13:	learn: 0.4845248	total: 63.6ms	remaining: 4.48s
14:	learn: 0.4639622	total: 63.9ms	remaining: 4.2s
15:	learn: 0.4432597	total: 64.1ms	remaining: 3.94s
16:	learn: 0.4251080	total: 64.3ms	remaining: 3.72s
17:	learn: 0.4095535	total: 64.6ms	remaining: 3.52s
18:	learn: 0.3929013	total: 64.8ms	remaining: 3.3

In [19]:
model5 = LGBMClassifier()
model5.fit(X_train,y_train)
y_pred5=model5.predict(X_test)
print("accuracy_Score:",accuracy_score(y_test,y_pred5))
print(classification_report(y_test,y_pred5))
print("confusion_matrix:",confusion_matrix(y_test,y_pred5))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000155 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 91
[LightGBM] [Info] Number of data points in the train set: 120, number of used features: 4
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -1.073920
[LightGBM] [Info] Start training from score -1.123930
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No furth